# This workflow will push docker image of the app to docker hub

name: Push to docker hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:   
    - name: checkout code
      uses: actions/checkout@v3
    
    #Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push to registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: anouarelanda/monapp-react:latest
        context: .
      
 

  
